# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thettapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('teamID', models.AutoField(primary_key=True, serialize=False)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_team_1', to='thettapp.player')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_team_2', to='thettapp.player')),
            ],
        ),
    ]
