# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thettapp', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='match',
            fields=[
                ('matchID', models.AutoField(primary_key=True, serialize=False)),
                ('matchType', models.CharField(blank=True, max_length=15, null=True)),
                ('team1Score', models.IntegerField(default=0)),
                ('team2Score', models.IntegerField(default=0)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_match', to='thettapp.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_match', to='thettapp.team')),
            ],
        ),
    ]
